### PR TITLE
ADD: add command replace-all-markdown-links-with-wikilinks

### PR DESCRIPTION
**Pull request by jiyee**
Fix: #47 #43 #18

### CODE REVIEW

**Comment by jiyee** [comment]
Current, the result of collect all attachments and moving file is different, Like:
F1/file.md contains assets/IMG.png, using wiki link like `![[IMG.png]]`, while attachment folder option is set "./assets"
while moving the F1/file.md to F2/file.md, the attachment will relocated in F2/IMG.png, not F2/assets/IMG.png.
perform collecting all attachments, the attachment will relocated in F2/assets/IMG.png.

**Comment by mnaoumov** [comment]
@jiyee thanks for your PR, but I don't think we are going to merge it because it goes against the philosophy of this plugin

If look at README it says

> "Use [[Wikilinks]]": disabled. Wikilinks are not a markdown standard.

If you look closely to https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/main.ts#L441 and https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/main.ts#L455, you will find that `Check Vault consistency' command considers wiki links and wiki embeds as the issues to be fixed, unlike your PR.

Moreover, the functionality you suggested to add, is already covered by another plugin https://github.com/ozntel/obsidian-link-converter and some other similar ones.

**Comment by jiyee** [comment]
> @jiyee thanks for your PR, but I don't think we are going to merge it because it goes against the philosophy of this plugin
> 
> If look at README it says
> 
> > "Use [[Wikilinks]]": disabled. Wikilinks are not a markdown standard.
> 
> If you look closely to https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/main.ts#L441 and https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/main.ts#L455, you will find that `Check Vault consistency` command considers wiki links and wiki embeds as the issues to be fixed, unlike your PR.
> 
> Moreover, the functionality you suggested to add, is already covered by another plugin https://github.com/ozntel/obsidian-link-converter and some other similar ones.

OK, I got it.

But, take a look at the bugfix commit to see if it is a bug or not? https://github.com/dy-sh/obsidian-consistent-attachments-and-links/pull/68/commits/e324a48fb4330204b2587dd5274f184354f44c6e

**Comment by mnaoumov** [comment]
@jiyee, yes, this seems to be a bug. Please create a proper bug report issue describing the use case and the PR to address the issue. Please also don't mix commits with actual fixes and fixing typos

**Pull request closed without merging**
