### PR TITLE
Add command 'Collect attachments in current note'

### LINKED ISSUE #23: Add command to collect attachments only in current note

### PR DESCRIPTION
**Pull request by mnaoumov**
Fixes #23

### CODE REVIEW

**Comment by dy-sh** [comment]
Thank you!

**Comment by mnaoumov** [comment]
@dy-sh I am sorry I just realized I forgot to rebase my PR and accidentally included pr #22 into the current one. If needed, I can separate those

**Comment by dy-sh** [comment]
Did I understand correctly that both pull requests have the same code?

**Comment by mnaoumov** [comment]
No, for PR #24 we need only one commit https://github.com/dy-sh/obsidian-consistent-attachments-and-links/pull/24/commits/b7e8798ab4801b3e552e74a3cf005ad0fea6ed35

Two others commits belong to PR #22 and there is also a one more commit I added there later

**Comment by dy-sh** [comment]
Ok, I've merged the second pull request and now it looks like I've added all your features.

**Comment by dy-sh** [comment]
This is great functionality, thanks.

**Comment by dy-sh** [comment]
I will update the plugin in the repository a bit later.

**Pull request merged**
